### ISSUE TITLE
Regarding Char offset

### ISSUE THREAD

**Issue by tahmedge** [google-research-datasets/natural-questions#16]
I cannot understand the char offset included in the BERT-BASELINE code. Why HTML tokens were not considered while calculating the offset values. Can you please elaborate?

**Comment by tomkwiat** [comment]
Hi Tahmid, it might be better to ask this question on the BERT baseline repository, rather than this dataset repository.

I believe that the original BERT baseline ignored HTML tokens, but I'm not sure how that was implemented.
