### ISSUE TITLE
Running nq_browser.py on Windows OS

### ISSUE THREAD

**Issue by bicachu** [google-research-datasets/natural-questions#17]
I'm having trouble running the nq_browser.py on my Windows 10 machine. There seems to be a lot of module or parts of the script that don't work in windows OS. Are there any workarounds or alternatives to run on Windows OS?

**Comment by tomkwiat** [comment]
I'm afraid that this has never been tested with Windows.

**Comment by ChangxinTian** [comment]
The same problem occurred on my machine

**Comment by bicachu** [comment]
@ChangxinTian  If it helps - I wasn't able to get it to work as it requires a lot of changes and module installations/removals to get it to work on Windows. However, if you run it on a VM or Linux machine it should work.

**Comment by MichaelBarz** [comment]
I just ran `nq_browser.py` it on my Windows 10 machine. Here are my system details:

- Python 2.7 (I'm using Anaconda) 
- `pip install` all modules that are listed in the comments on `nq_browser.py`
- `conda install numpy`
- change [this line](https://github.com/google-research-datasets/natural-questions/blob/a7d6452c0905c7772e9fbbb9a20b5fcab07c668f/nq_browser.py#L372) in the main function: change `with open(FLAGS.nq_jsonl) as fileobj:` to `with open(FLAGS.nq_jsonl, mode="rb") as fileobj:`

If the line in `main`is not changed and you try to open a gzipped file from the dataset, you'll receive a `zlib.error: Error -3 while decompressing: invalid distance too far back`.
