### ISSUE TITLE
pre-processing code for document_html to document_tokens

### ISSUE THREAD

**Issue by jhyuklee** [google-research-datasets/natural-questions#19]
Hi, I'm looking for the code for pre-processing `document_html` to `document_tokens`. When I just join the `document_tokens` using whitespace, the resulting document is different from what I have in the original Wikipedia article.

For instance `document_tokens` with whitespace join looks like (say, format 1):
`It is mostly water ( up to 95 % by volume ) , and contains dissolved proteins ( 6 -- 8 % )`

while the same part I get from WikiExtractor (https://github.com/attardi/wikiextractor) is (format 2):
`It is mostly water (up to 95% by volume), and contains dissolved proteins (6\u20138%)`

Since I want to inference on the articles from WikiExtractor, I need to change format 1 to format 2 (or vice versa) for NQ training, or `document_html` to format 2 while keeping the answer annotations.
For me, **converting `document_html` to format 2 while keeping the answer annotations** will be the best option.

Thanks.

**Comment by shivashankarrs** [comment]
@jhyuklee did you find a solution for your question. Also is there any code to generate document_tokens from html source.
